import { User } from '@chess-tent/models';

const coaches: User[] = [
  {
    id: '1',
    type: 'users',
    active: true,
    nickname: 'coach-f3ea0b',
    name: 'Coachy McCoachFace',
    email: 'coach1@chesstent+f3ea0b.com',
    coach: true,
    password: 'testpassword1',
    state: {
      imageUrl:
        'SET_VALUE/577e775a-da49-404f-8a96-33c63a2c38e4?t=1694446412674',
      about: 'about1',
      availability: 'availability1',
      country: 'RO',
      pricing: '1',
      elo: 5554,
      languages: ['Sorani', 'Berber', 'Arabic'],
      playingExperience: 'playingExperience1',
      punchline: 'punchline1',
      speciality: 'speciality1',
      studentEloMax: 2400,
      studentEloMin: 500,
      teachingExperience: 'teachingExperience1',
      teachingMethodology: 'method1',
    },
  },
  {
    id: '2',
    type: 'users',
    active: true,
    nickname: 'coach-62f8d1',
    name: 'John Doe',
    email: 'coach2@chesstent+62f8d1.com',
    coach: true,
    password: 'testpassword2',
    state: {
      imageUrl:
        'SET_VALUE/123e4567-e89b-12d3-a456-426614174000?t=1694446412674',
      about: 'about',
      availability: 'availability',
      country: 'US',
      pricing: '2',
      elo: 2000,
      languages: ['English', 'Spanish'],
      playingExperience: 'playingExperience',
      punchline: 'punchline',
      speciality: 'speciality',
      studentEloMax: 2200,
      studentEloMin: 1000,
      teachingExperience: 'teachingExperience',
      teachingMethodology: 'teachingMethodology',
    },
  },
  {
    id: '3',
    type: 'users',
    active: true,
    nickname: 'coach-987cde',
    name: 'Jane Smith',
    email: 'coach3@chesstent+987cde.com',
    coach: true,
    password: 'testpassword3',
    state: {
      imageUrl:
        'SET_VALUE/789abcde-1234-5678-9012-345678901234?t=1694446412674',
      about: 'about',
      availability: 'availability',
      country: 'CA',
      pricing: '10',
      elo: 3000,
      languages: ['English', 'French'],
      playingExperience: 'playingExperience',
      punchline: 'punchline',
      speciality: 'speciality',
      studentEloMax: 2500,
      studentEloMin: 1500,
      teachingExperience: 'teachingExperience',
      teachingMethodology: 'teachingMethodology',
    },
  },
  {
    id: '4',
    type: 'users',
    active: true,
    nickname: 'coach-abcdef',
    name: 'Sarah Johnson',
    email: 'coach4@chesstent+abcdef.com',
    coach: true,
    password: 'testpassword4',
    state: {
      imageUrl:
        'SET_VALUE/abcdef12-3456-7890-abcd-ef1234567890?t=1694446412674',
      about: 'about',
      availability: 'availability',
      country: 'AU',
      pricing: '3',
      elo: 4000,
      languages: ['English'],
      playingExperience: 'playingExperience',
      punchline: 'punchline',
      speciality: 'speciality',
      studentEloMax: 2600,
      studentEloMin: 2000,
      teachingExperience: 'teachingExperience',
      teachingMethodology: 'teachingMethodology',
    },
  },
  {
    id: '5',
    type: 'users',
    active: true,
    nickname: 'coach-a4eb0c',
    name: 'Coachy McTwo',
    email: 'coach2@chesstent+f4eb0c.com',
    coach: true,
    password: 'testpassword2',
    state: {
      imageUrl:
        'SET_VALUE/477f865b-da59-405f-9a87-22d53b3c39e5?t=1694446412685',
      about: 'about2',
      availability: 'availability2',
      country: 'US',
      pricing: '4',
      elo: 5564,
      languages: ['English', 'Spanish'],
      playingExperience: 'playingExperience2',
      punchline: 'punchline2',
      speciality: 'speciality2',
      studentEloMax: 2450,
      studentEloMin: 505,
      teachingExperience: 'teachingExperience2',
      teachingMethodology: 'method2',
    },
  },
  {
    id: '6',
    type: 'users',
    active: true,
    nickname: 'coach-f3ea0bs',
    name: 'Coachy McCoachFace',
    email: 'coach1@chesstent+f3ea0bs.com',
    coach: true,
    password: 'testpassword1',
    state: {
      imageUrl:
        'SET_VALUE/577e775a-da49-404f-8a96-33c63a2c38e4?t=1694446412674',
      about: 'about',
      availability: 'availability',
      country: 'RO',
      pricing: '5',
      elo: 5554,
      languages: ['Sorani', 'Berber', 'Arabic'],
      playingExperience: 'playingExperience',
      punchline: 'punchline',
      speciality: 'speciality',
      studentEloMax: 2400,
      studentEloMin: 500,
      teachingExperience: 'teachingExperience',
      teachingMethodology: 'teachingMethodology',
    },
  },
  {
    id: '7',
    type: 'users',
    active: true,
    nickname: 'coach-a5db2f',
    name: 'Coachella Coach',
    email: 'coach10@chesstent+a5db2f.com',
    coach: true,
    password: 'testpassword10',
    state: {
      imageUrl:
        'SET_VALUE/488f8f5b-ea52-444f-8a97-44c73a3c47f5?t=1694446412780',
      about: 'about10',
      availability: 'weekday evenings',
      country: 'UK',
      pricing: '6',
      elo: 5604,
      languages: ['English', 'French', 'German'],
      playingExperience: '10 years',
      punchline: 'Keep calm and play on!',
      speciality: 'Opening theory',
      studentEloMax: 2500,
      studentEloMin: 520,
      teachingExperience: '5 years',
      teachingMethodology: 'Analytical',
    },
  },
  {
    id: '8',
    type: 'users',
    active: true,
    nickname: 'coach-987654',
    name: 'Emily Wilson',
    email: 'coach6@chesstent+987654.com',
    coach: true,
    password: 'testpassword6',
    state: {
      imageUrl:
        'SET_VALUE/abcdef12-3456-7890-abcd-ef1234567890?t=1694446412674',
      about: 'about',
      availability: 'availability',
      country: 'AU',
      pricing: '7',
      elo: 2800,
      languages: ['English', 'German'],
      playingExperience: 'playingExperience',
      punchline: 'punchline',
      speciality: 'speciality',
      studentEloMax: 2300,
      studentEloMin: 1500,
      teachingExperience: 'teachingExperience',
      teachingMethodology: 'teachingMethodology',
    },
  },
  {
    id: '9',
    type: 'users',
    active: true,
    nickname: 'coach-654321',
    name: 'David Thompson',
    email: 'coach7@chesstent+654321.com',
    coach: true,
    password: 'testpassword7',
    state: {
      imageUrl:
        'SET_VALUE/abcdef12-3456-7890-abcd-ef1234567890?t=1694446412674',
      about: 'about',
      availability: 'availability',
      country: 'US',
      pricing: '8',
      elo: 3800,
      languages: ['English'],
      playingExperience: 'playingExperience',
      punchline: 'punchline',
      speciality: 'speciality',
      studentEloMax: 3000,
      studentEloMin: 2000,
      teachingExperience: 'teachingExperience',
      teachingMethodology: 'teachingMethodology',
    },
  },
  {
    id: '10',
    type: 'users',
    active: true,
    nickname: 'coach-1a2b3c',
    name: 'Jessica Lee',
    email: 'coach8@chesstent+1a2b3c.com',
    coach: true,
    password: 'testpassword8',
    state: {
      imageUrl:
        'SET_VALUE/abcdef12-3456-7890-abcd-ef1234567890?t=1694446412674',
      about: 'about',
      availability: 'availability',
      country: 'CA',
      pricing: '9',
      elo: 4200,
      languages: ['English', 'French'],
      playingExperience: 'playingExperience',
      punchline: 'punchline',
      speciality: 'speciality',
      studentEloMax: 3800,
      studentEloMin: 2500,
      teachingExperience: 'teachingExperience',
      teachingMethodology: 'teachingMethodology',
    },
  },
];

export { coaches };
