#!/bin/sh
. "$(dirname $0)/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" "*.ts" "*.tsx" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --config ./.prettierrc --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
